language: php

php:
  - 7.2
  - 7.3

sudo: false

install:
  - travis_retry composer install --no-interaction

script:
  - mkdir -p .docker/.ssl
  - openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout .docker/.ssl/server.key -out .docker/.ssl/server.pem -subj "/C=IT/ST=Sicily/L=Ortygia/O=dontvis.it/OU=IT Department/CN=localhost"
  - npm install --silent
  - npm run prod &> /dev/null
  - docker-compose pull
  - docker-compose up -d
  - mkdir -p storage/views
  - chmod a+w storage/views
  - while ! docker-compose exec web echo 'up'; do sleep 1; done
  - while ! docker-compose run mysql sh -c "mysql -uroot -ppassword -h mysql --execute 'use dontvisit;'"; do sleep 1; done
  - vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)
