language: php

php:
  - 7.2
#  - 7.3

sudo: false

services:
  - docker

install:
  - travis_retry composer install --no-interaction

script:
  - docker-compose pull
  - docker-compose up -d
  - docker-compose ps
  - ping localhost
  - docker-compose exec web echo 'up'
  - while ! docker-compose exec web echo 'up'; do sleep 1; done
  - docker-compose run php sh -c "/app/vendor/bin/phpunit /app/tests"
  #- docker-compose run php sh -c "/app/vendor/bin/phpunit /app/tests --coverage-clover /app/clover.xml"
  #  - vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)
