web:
  container_name: web
  image: nginx:latest
  ports:
    #- "8080:80"
    - "3000:443"
  volumes:
    - ./:/app
    - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./.docker/.ssl:/ssl
  links:
    - php

php:
  container_name: php-fpm
  image: devilbox/php-fpm:7.2-mods-release-0.105
  volumes:
    - ./:/app
  environment:
    XDEBUG_CONFIG: remote_host=host.docker.internal
  links:
    - mysql

mysql:
  container_name: mysql
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    - MYSQL_DATABASE=${DB_NAME}
  volumes:
    - ./.docker/.mysql-data:/var/lib/mysql

phpmyadmin:
  container_name: phpmyadmin
  image: phpmyadmin/phpmyadmin:latest
  links:
    - mysql:db
  ports:
    - "8082:80"
  environment:
    - PMA_USER=${DB_USER}
    - PMA_PASSWORD=${DB_PASSWORD}
    - PHP_UPLOAD_MAX_FILESIZE=100MB
